import os

# global constants
END_DATA_BLOCK_INDICATION_STRING = 'EB'
ELIMINATION_BLOCK_INDICATION_STRING = 'EL'
NQST = 'ST'
DOWNWEIGHT_BLOCK_INDICATION_STRING = 'MO'
FISSION_SPECTRUM_BLOCK_INDICATION_STRING = 'FI'

# global vars
MAXF = 900

MAX_NUM_POINTS = 1000
MAX_NUM_REACTIONS = 1000

# LIMIT OF DIF/UNC FOR OUTLIERS?
ULI = 3.0

NQMM = 0

# Enables output with more precision to facilitate testing
try:
    SHOULD_TEST_OUTPUT = (os.environ['TEST_DATP'] == 'yes')
except KeyError:
    SHOULD_TEST_OUTPUT = False


if not SHOULD_TEST_OUTPUT:
    FORMAT200 = '(2E10.4,12F5.1)'
    FORMAT290 = '(2E10.4,12F5.1,F7.3)'
else:
    FORMAT200 = '(2E14.6,12F12.7)'
    FORMAT290 = '(2E14.6,12F12.7,F9.5)'

FORMAT250 = '(4HEDBL,1X,2I5)'
