# generated by datamodel-codegen:
#   filename:  schema_fission_spectrum_base_v0_0_1.json
#   timestamp: 2025-06-13T08:47:12+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, constr


class FissionSpectrumBase(BaseModel):
    label: constr(min_length=16, max_length=16)
    energies: List[float]
    spectrum_values: List[float]
