# generated by datamodel-codegen:
#   filename:  schema_reaction_prior_base_v0_0_1.json
#   timestamp: 2025-03-27T21:50:15+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel


class ReactionPriorBase(BaseModel):
    energy_mesh: List[List[float]]
    cross_section: List[List[float]]
    label: List[str]
