# generated by datamodel-codegen:
#   filename:  schema_reaction_prior_base_v0_0_1.json
#   timestamp: 2025-06-13T08:47:14+00:00

from __future__ import annotations

from typing import Dict, List, Optional

from pydantic import BaseModel, Field, RootModel, conint, constr


class ReactionPriorBase1(BaseModel):
    label: constr(min_length=16, max_length=16)
    reaction_id: Optional[conint(ge=1)] = None
    energies: List[float]
    cross_sections: List[float]


class ReactionPriorBase(
    RootModel[Dict[constr(pattern=r'^[0-9]+$'), ReactionPriorBase1]]
):
    root: Dict[constr(pattern=r'^[0-9]+$'), ReactionPriorBase1] = Field(
        ...,
        description='List of energy-dependent cross sections with prior values',
        title='ReactionPriorBase',
    )
